name: Build on master

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            10.0.x

      - name: Restore
        run: dotnet restore ./Xtb.Toolkit.slnx --configfile ./nuget.config

      - name: Build
        run: dotnet build ./Xtb.Toolkit.slnx -c Release --no-restore
